/**
 * Arabic labels and hints for the admin forms. Forms are generated from the Zod
 * schemas, so a new field only needs a label here (it falls back to the key name).
 *
 * Lookup order: exact path ("hero.primaryCta.message"), then generic path with
 * array indexes removed ("exams.items.title"), then the bare key ("title").
 */

const BY_KEY: Record<string, string> = {
  // common
  eyebrow: "عنوان صغير فوق القسم",
  title: "العنوان",
  intro: "مقدمة القسم",
  text: "النص",
  label: "النص الظاهر",
  message: "رسالة الواتساب الجاهزة",
  ref: "كود تتبع الزر",
  href: "الرابط",
  url: "الرابط",
  cta: "زر التواصل",
  name: "الاسم",
  id: "المعرّف (بالإنجليزي، بدون مسافات)",
  note: "ملاحظة",
  style: "شكل النص",
  value: "القيمة",
  prefix: "علامة قبل الرقم",
  caption: "وصف قصير",
  // profile
  profile: "الملف الشخصي",
  fullTitle: "اللقب الكامل",
  latinName: "الاسم بالإنجليزي",
  role: "الوصف المهني",
  photo: "الصورة",
  avatar: "صورة مصغّرة (أيقونة)",
  logo: "اللوجو",
  photoBadge: "شارة على الصورة",
  replyNote: "ملاحظة الرد",
  // contact
  contact: "التواصل",
  primary: "تطبيق التواصل الأساسي",
  whatsapp: "رقم الواتساب (دولي بدون +، مثل 2010...)",
  telegram: "اسم مستخدم تيليجرام",
  messenger: "اسم صفحة فيسبوك (ماسنجر)",
  phones: "أرقام الهاتف الظاهرة",
  phoneHighlights: "تلوين أرقام معيّنة (متقدم)",
  refCodes: "إضافة كود تتبع للرسائل",
  refLabel: "كلمة الكود في الرسالة",
  // socials / nav
  socials: "روابط السوشيال ميديا",
  type: "المنصة",
  nav: "روابط القائمة العلوية",
  navCta: "زر القائمة العلوية",
  sections: "الأقسام الظاهرة وترتيبها",
  seo: "جوجل والمشاركة",
  description: "الوصف",
  ogImage: "صورة المشاركة (واتساب/فيسبوك)",
  locale: "اللغة (مثل ar-EG)",
  dir: "اتجاه الكتابة",
  slug: "المعرّف",
  // hero
  hero: "الواجهة الرئيسية",
  kicker: "سطر فوق العنوان",
  headline: "العنوان الرئيسي (كل عنصر سطر)",
  lede: "الفقرة التعريفية",
  primaryCta: "الزر الأساسي",
  secondaryCta: "الزر الثانوي",
  stats: "الأرقام",
  // grades
  grades: "الصفوف والمواد",
  stages: "المراحل",
  items: "العناصر",
  subject: "المادة",
  // schedule
  schedule: "جدول المواعيد",
  location: "المكان",
  filters: "أزرار التصفية",
  stage: "المرحلة",
  day: "اليوم",
  labels: "نصوص ثابتة",
  slots: "المواعيد",
  grade: "الصف",
  days: "الأيام",
  time: "الساعة",
  mode: "نوع الحصة (سنتر/أونلاين)",
  messages: "رسائل الواتساب",
  all: "الكل",
  pm: "مساءً",
  am: "صباحاً",
  tbd: "لم يحدد بعد",
  empty: "لا توجد مواعيد",
  book: "حجز",
  ask: "استفسار",
  // method
  method: "طريقة الشرح",
  icon: "الأيقونة",
  // book
  seriesName: "اسم السلسلة",
  cover: "صورة الغلاف",
  backCover: "الغلاف الخلفي",
  coverAlt: "وصف الغلاف (لجوجل وقارئ الشاشة)",
  features: "المميزات",
  order: "نموذج طلب الكتاب",
  gradeLabel: "عنوان اختيار الصف",
  deliveryLabel: "عنوان طريقة الاستلام",
  delivery: "طرق الاستلام",
  notePhone: "رقم يظهر مع الملاحظة",
  // students
  students: "الطلاب",
  count: "عدد الطلاب",
  gallery: "صور مع الطلاب (حصص، رحلات، ماتشات)",
  image: "الصورة",
  alt: "وصف الصورة (لجوجل وقارئ الشاشة)",
  pages: "صفحات من داخل الكتاب",
  pagesTitle: "عنوان فوق صفحات الكتاب",
  area: "المنطقة",
  center: "السنتر",
  // challenge
  challenge: "تحدي الأسئلة",
  sendLabel: "نص زر الإرسال",
  questions: "الأسئلة",
  level: "المستوى",
  question: "السؤال",
  options: "الاختيارات",
  draft: "سؤال تجريبي (غير نهائي)",
  // exams
  exams: "الامتحانات",
  date: "التاريخ",
  featured: "إعلان مميز (شريط أحمر وعداد)",
  place: "المكان",
  fee: "الرسوم",
  prize: "الجائزة",
  tracks: "المستويات/الصفوف",
  scope: "المقرر",
  announcement: "نص الشريط الأحمر ({date} = التاريخ)",
  trackLabel: "عنوان اختيار المستوى",
  countdown: "عنوان العداد",
  hours: "ساعات",
  minutes: "دقائق",
  today: "النهاردة",
  // youtube
  youtube: "قناة اليوتيوب",
  channelName: "اسم القناة",
  channelUrl: "رابط القناة",
  subscribeLabel: "نص زر الاشتراك",
  videos: "الفيديوهات",
  showSocials: "عرض روابط السوشيال ميديا في القسم",
  socialsTitle: "جملة فوق روابط السوشيال",
  followersTotal: "إجمالي المتابعين (مثل +5000)",
  followersLabel: "وصف الرقم",
  followers: "عدد المتابعين (مثل +2000)",
  // reviews
  reviews: "آراء الطلاب",
  metric: "الرقم الكبير",
  stars: "إظهار النجوم",
  images: "صور الآراء",
  moreLabel: "نص زر عرض الكل",
  // services
  services: "خدمات أخرى",
  // popup
  popup: "الإعلان المنبثق",
  enabled: "مفعّل",
  video: "رابط فيديو يوتيوب (اختياري)",
  endsAt: "يختفي تلقائياً بعد",
  delaySeconds: "يظهر بعد (ثواني)",
  remindAfterHours: "يظهر مرة أخرى لنفس الزائر بعد (ساعات)",
  to: "الرقم أو اسم المستخدم أو الرابط",
  announcementEnds: "إخفاء الشريط الأحمر بعد",
  announcementStarts: "إظهار الشريط الأحمر من",
  startsAt: "يبدأ الظهور من",
  // quizzes
  quizzes: "الاختبارات",
  durationMinutes: "مدة الاختبار (دقائق)",
  state: "الحالة",
  passPercent: "نسبة النجاح %",
  startLabel: "نص زر البدء",
  doneMessage: "رسالة بعد التسليم",
  correct: "الإجابات الصحيحة",
  points: "درجة السؤال",
  // forms
  forms: "النماذج",
  form: "عند الضغط على الزر",
  fields: "الأسئلة",
  required: "إجباري",
  remember: "تذكّر الإجابة على جهاز الطالب",
  placeholder: "نص توضيحي داخل الخانة",
  submitLabel: "نص زر الإرسال",
  successMessage: "رسالة بعد الإرسال",
  // final / footer / sticky
  final: "الدعوة الأخيرة",
  footer: "الفوتر",
  hashtags: "الهاشتاجات",
  sticky: "الشريط السفلي الثابت",
  secondary: "الزر الثانوي",
  daysJoiner: "فاصل الأيام",
  sat: "السبت", sun: "الأحد", mon: "الاثنين", tue: "الثلاثاء", wed: "الأربعاء", thu: "الخميس", fri: "الجمعة",
  // theme
  scheme: "الوضع",
  colors: "الألوان",
  bg: "الخلفية", surface: "خلفية البطاقات", raised: "خلفية مرتفعة", line: "الخطوط الفاصلة",
  accent: "اللون الأساسي", accentHot: "اللون الأساسي (عند التمرير)", accentDeep: "اللون الأساسي الداكن", onAccent: "لون النص فوق الأساسي",
  muted: "نص ثانوي", subtle: "نص باهت", online: "لون أونلاين",
  fonts: "الخطوط", googleFontsHref: "رابط Google Fonts", display: "خط العناوين", body: "خط النصوص", numeric: "خط الأرقام",
  radius: "استدارة الحواف", card: "البطاقات", control: "الحقول", pill: "الأزرار",
  texture: "ملمس الخلفية", glow: "توهج الخلفية", heroPhotoShape: "شكل صورة الواجهة", tagRotation: "ميل الكلمة المميزة", buttonGlow: "توهج الأزرار",
};

const BY_PATH: Record<string, string> = {
  "contact.primary": "تطبيق التواصل الأساسي",
  "schedule.labels.book": "نص زر الحجز",
  "schedule.labels.ask": "نص زر الاستفسار",
  "schedule.labels.stage": "عنوان تصفية المرحلة",
  "schedule.labels.day": "عنوان تصفية اليوم",
  "schedule.messages.book": "رسالة الحجز",
  "schedule.messages.ask": "رسالة الاستفسار",
  "schedule.filters.stage": "تصفية بالمرحلة",
  "schedule.filters.day": "تصفية باليوم",
  "schedule.filters.area": "تصفية بالمنطقة",
  "schedule.labels.area": "عنوان تصفية المنطقة",
  "schedule.location": "المكان الافتراضي",
  "challenge.prize": "الجائزة (سطر مميز في القسم)",
  "youtube.videos.id": "رابط الفيديو",
  "youtube.videos.title": "عنوان الفيديو",
  "schedule.slots.stage": "المرحلة (معرّف المرحلة من قسم الصفوف)",
  "exams.labels.days": "أيام",
  "exams.labels.scope": "عنوان المقرر",
  "exams.labels.prize": "عنوان الجائزة",
  "exams.items.cta": "نص زر الحجز",
  "exams.items.title": "اسم الامتحان",
  "exams.items.message": "رسالة الحجز",
  "book.order.grades": "الصفوف المتاحة",
  "book.order.cta": "نص زر الطلب",
  "book.order.message": "رسالة الطلب",
  "book.order.whatsapp": "رقم واتساب خاص بالطلبات (اختياري)",
  "book.order.title": "عنوان النموذج",
  "book.features.value": "الرقم/القيمة",
  "book.features.label": "الوصف",
  "hero.stats.value": "الرقم",
  "hero.stats.label": "الوصف",
  "grades.stages.items": "الصفوف",
  "grades.stages.items.name": "الصف",
  "labels.days": "أسماء الأيام",
  "sticky.cta": "الزر الأساسي",
  // theme page (its fields sit at the root of the form)
  "name": "اسم الهوية",
  "colors.text": "لون النص",
  "challenge.message": "رسالة إرسال الإجابة",
  "socials.note": "جملة قصيرة: الطالب هيستفيد إيه من المنصة دي",
  "services.items.socials.note": "جملة قصيرة عن الرابط",
  "popup.cta": "زر (اختياري)",
  "popup.text": "النص",
  "services.items.cta": "زر التواصل",
  "services.items.image": "الصورة",
  "reviews.metric.value": "الرقم (مثل +100)",
  "reviews.metric.label": "الوصف (مثل تقييم من الطلاب وأولياء الأمور)",
  "reviews.images.alt": "وصف الصورة (اختياري)",
  "popup.cta.type": "يفتح",
  "services.items.cta.type": "يفتح",
  "popup.cta.message": "رسالة جاهزة (واتساب وتيليجرام فقط)",
  "services.items.cta.message": "رسالة جاهزة (واتساب وتيليجرام فقط)",
};

const HINTS: Record<string, string> = {
  "schedule.messages.book": "يمكن استخدام {grade} و{subject} و{days} و{time} و{location} (السنتر) و{area} (المنطقة).",
  "schedule.messages.ask": "تُستخدم للمواعيد التي لم تحدد ساعتها. يمكن استخدام {grade} و{subject} و{location} (السنتر) و{area} (المنطقة).",
  "schedule.location": "يظهر للمجموعات اللي مش محدد لها سنتر.",
  "schedule.slots.area": "مثل: فيصل. يظهر في كارت المجموعة وفي أزرار التصفية.",
  "schedule.slots.center": "مثل: سنتر الأوائل. لو فاضي يُستخدم المكان الافتراضي.",
  "schedule.filters.area": "تظهر فقط لو المجموعات في أكتر من منطقة.",
  "students.gallery": "تظهر تحت القسم، والزائر يقدر يكبّر أي صورة.",
  "book.pages": "صور لصفحات من جوه الكتاب عشان الطالب يشوف شكل الشرح. الزائر يقدر يكبّرها.",
  "challenge.prize": "مثال: حل صح وابعت إجابتك على واتساب واكسب ... يمكن استخدامها في الرسالة بـ {prize}.",
  "youtube.videos.id": "الصق رابط الفيديو من يوتيوب (أي شكل: watch أو youtu.be أو shorts).",
  "exams.items.message": "يمكن استخدام {date} و{track} و{scope}.",
  "exams.items.date": "يختفي الامتحان من الموقع تلقائياً بعد يومه.",
  "exams.items.id": "مثال: OCT-U1. يظهر في كود التتبع.",
  "book.order.message": "يمكن استخدام {grade} و{delivery}.",
  "challenge.message": "يمكن استخدام {n} (رقم السؤال) و{answer} (الإجابة) و{prize} (الجائزة).",
  "contact.whatsapp": "مثال: 201009719950",
  "contact.refCodes": "يضيف (كود: XXX) لآخر الرسالة لتعرف أي زر استخدمه الطالب.",
  "sections": "الترتيب هنا هو ترتيب ظهور الأقسام في الموقع.",
  "seo.title": "يظهر في جوجل وفي عنوان التبويب. الأفضل أقل من 60 حرف.",
  "seo.description": "يظهر تحت العنوان في جوجل. الأفضل 120-160 حرف.",
  "hero.headline": "كل عنصر سطر. يمكن تمييز كلمة بلون أو بإطار.",
  "students.photo": "اختياري. بدون صورة يظهر الرقم فقط.",
  "nav.href": "مثل #schedule للانتقال لقسم في الصفحة.",
  "contact.phoneHighlights": "بصيغة JSON: رقم الهاتف ← مواضع الأرقام الملوّنة.",
  "quizzes.path": "الاختبار هيكون على عنوان الموقع/الاسم ده، مثل exam-oct. حروف إنجليزية وأرقام وشرطة.",
  "quizzes.form": "النموذج اللي الطالب يملاه قبل ما يبدأ (الاسم، الرقم...). لو فيه رقم موبايل، كل رقم يدخل الاختبار مرة واحدة.",
  "quizzes.durationMinutes": "الوقت بيبدأ لما الطالب يضغط ابدأ. 0 = بدون وقت (يفضل مفتوح لحد تاريخ الانتهاء).",
  "quizzes.state": "«تلقائي» = مفتوح بين تاريخ البداية والنهاية. «مفتوح الآن» و«مقفول» بيتجاهلوا التواريخ. تقدر تغيّرها بزرار من صفحة الاختبارات.",
  "quizzes.startsAt": "فارغ = متاح فوراً.",
  "quizzes.endsAt": "بعده محدش يقدر يبدأ، واللي بيحل وقته بيخلص.",
  "quizzes.questions": "متغيرش ترتيب الأسئلة بعد ما الطلاب يبدأوا (الإجابات متسجلة برقم السؤال). أي سؤال ممكن يتساب فاضي.",
  "quizzes.questions.options": "للنوع «اختيار من متعدد».",
  "quizzes.questions.correct": "اختيارية، والطالب مش بيشوفها. اختيار من متعدد: انسخ الاختيار الصحيح زي ما هو. نص مكتوب: اكتب كل الصيغ المقبولة (المسافات وحالة الحروف والتشكيل مش بتفرق). فاضية = السؤال مش بيتصحح.",
  "quizzes.questions.image": "صورة للسؤال (اختياري)، مثلاً رسمة أو مسألة مصورة.",
  "forms": "كل نموذج له معرّف بالإنجليزي. بعد إنشائه، اختره من خانة «عند الضغط على الزر» في أي زر واتساب (الواجهة، الجدول، الكتاب، الامتحانات، التحدي...). الطلبات بتظهر في صفحة «الطلبات».",
  "forms.id": "مثل student-info. ميتغيرش بعد ما تستخدمه في الأزرار.",
  "forms.fields.id": "بالإنجليزي، مثل name أو phone. نفس المعرّف في نموذجين = الطالب ميكتبهوش مرتين.",
  "forms.fields.remember": "شغّلها لبيانات الطالب الثابتة (الاسم، الرقم، الصف) عشان متتسألش تاني. اقفلها للإجابات اللي بتتغير كل مرة.",
  "forms.fields.options": "للنوع «اختيار من قائمة» فقط.",
  "forms.fields.type": "«رقم موبايل» بيتأكد إن الرقم صحيح.",
  "popup.startsAt": "فارغ = يظهر فوراً. لو حددت الساعة يبدأ في الساعة دي.",
  "exams.announcementStarts": "فارغ = يظهر فوراً.",
  "popup": "يظهر فوق الصفحة بعد فتحها (على الموبايل يظهر من أسفل الشاشة). لو فيه فيديو يظهر بدل الصورة.",
  "popup.endsAt": "بعد التاريخ ده الإعلان يختفي من الموقع لوحده. لو حددت الساعة يختفي في الساعة دي.",
  "popup.remindAfterHours": "لو الزائر قفل الإعلان، مش هيظهر له تاني إلا بعد المدة دي. أي تعديل في الإعلان يخليه يظهر للكل من جديد.",
  "popup.enabled": "اقفله لإخفاء الإعلان بدون حذفه.",
  "exams.announcementEnds": "اختياري. الشريط يختفي لوحده بعد التاريخ ده، وكمان بعد يوم الامتحان المميز.",
  "popup.cta.to": "واتساب: رقم دولي (فارغ = رقم الموقع). تيليجرام/ماسنجر: اسم المستخدم. اتصال: رقم الهاتف. رابط: https://...",
  "services.items.cta.to": "واتساب: رقم دولي (فارغ = رقم الموقع). تيليجرام/ماسنجر: اسم المستخدم. اتصال: رقم الهاتف. رابط: https://...",
  "socials.followers": "يظهر في قسم اليوتيوب مع الرابط.",
  "reviews.images": "صور سكرين شوت لرسائل وتقييمات الطلاب. أي عدد، وتترتب لوحدها.",
  "youtube.followersTotal": "مثال: +5000 متابع على كل منصاتنا. أعداد كل منصة تتكتب في قسم السوشيال ميديا.",
};

const ENUMS: Record<string, string> = {
  rtl: "من اليمين لليسار", ltr: "من اليسار لليمين",
  whatsapp: "واتساب", telegram: "تيليجرام", messenger: "ماسنجر",
  youtube: "يوتيوب", tiktok: "تيك توك", facebook: "فيسبوك", instagram: "إنستجرام", whatsappChannel: "قناة واتساب", x: "إكس (تويتر)",
  accent: "ملوّن", tag: "داخل إطار", strong: "عريض",
  hero: "الواجهة", grades: "الصفوف", schedule: "الجدول", method: "طريقة الشرح", book: "الكتاب", students: "الطلاب",
  challenge: "التحدي", exams: "الامتحانات", final: "الدعوة الأخيرة", reviews: "آراء الطلاب", services: "خدمات أخرى",
  phone: "اتصال", link: "رابط",
  tel: "رقم موبايل", number: "رقم", select: "اختيار من قائمة", textarea: "نص طويل",
  text: "نص مكتوب", choice: "اختيار من متعدد",
  auto: "تلقائي حسب التواريخ", open: "مفتوح الآن", closed: "مقفول",
  sat: "السبت", sun: "الأحد", mon: "الاثنين", tue: "الثلاثاء", wed: "الأربعاء", thu: "الخميس", fri: "الجمعة",
  chat: "محادثة", check: "علامة صح", loop: "تكرار", trophy: "كأس", bolt: "برق", star: "نجمة", users: "طلاب",
  dark: "داكن", light: "فاتح", grain: "حبيبات", none: "بدون", blob: "شكل حر", rounded: "حواف مستديرة", circle: "دائرة",
};

const generic = (path: string) => path.split(".").filter((p) => !/^\d+$/.test(p)).join(".");

export function labelFor(path: string, key: string): string {
  const g = generic(path);
  return BY_PATH[path] ?? BY_PATH[g] ?? BY_KEY[key] ?? key;
}

/** Hints that apply wherever a key appears (e.g. every button's "form"). */
const KEY_HINTS: Record<string, string> = {
  form: "واتساب = الطالب يبعت رسالة. نموذج = الطالب يكتب بياناته (ومعاها اختياره: الإجابة، المجموعة، الامتحان...) وتوصلك في صفحة «الطلبات» بدل الواتساب.",
};

export function hintFor(path: string): string | undefined {
  return HINTS[path] ?? HINTS[generic(path)] ?? KEY_HINTS[path.split(".").pop() ?? ""];
}

export function enumLabel(value: string): string {
  if (value === "book") return "كتاب";
  return ENUMS[value] ?? value;
}

export const sectionEnumLabel = (value: string) => (value === "book" ? "الكتاب" : enumLabel(value));
